
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/c-bata/go-prompt"
  version = "0.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/xwb1989/sqlparser"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.23"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.30.3"

[[constraint]]
  name = "gopkg.in/cheggaaa/pb.v2"
  version = "2.0.5"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/urfave/cli.v2"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "github.com/gernest/wow"
